# file: run.py
# generated by pangeo-forge.
import os
import sys
module = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, module)

import pipeline

pipe = pipeline.Pipeline()
flow = pipe.flow
flow.storage = pipe.storage
flow.environment = pipe.environment
