# file: run.py
# generated by pangeo-forge.
import sys
sys.path.insert(0, "")
import recipe.pipeline

pipeline = recipe.pipeline.Pipeline()
flow = pipeline.flow
flow.storage = pipeline.storage
flow.environment = pipeline.environment
